### ISSUE TITLE
Update paint style to match JOSM

### ISSUE THREAD

**Issue by zlavergne** [KaartGroup/GoKaart#9]
- [x] make alley, service, and driveway unique colors
- [x] tertiary to #408CCC
- [x] add dashed lines for links

**Comment by garylancelot** [comment]
New paint style to match JOSM where construction and proposed highway tags are more well-defined.

https://github.com/KaartGroup/Kaart-Styles/blob/4d7164eb345e7aeb7a7b60a65abd50ab0d842635/Kaart-Styles.mapcss#L383-L413
